#!/usr/bin/env python3
# Intended for Dev/Test environments only.
#
# api-verify script for module RPT — generated by the api-verify skill
# (.claude/skills/api-verify/SKILL.md). Regenerate it; never hand-edit it.
#
# It holds the module's published api-docs (plan.api_docs) to its API document
# (plan.api_spec, OpenAPI 3.1) by calling the RUNNING service end-to-end in
# dependency order. Every path is read through scripts/gov-module.py (the v7
# consumer contract); every response shape and error code is read from the API
# document at run time, never typed here.
#
# It never calls PUT / PATCH / DELETE, never writes to the database or a host
# system directly, never reaches a real host Approval API, and sends only
# synthetic, run-namespaced values.
#
#   python3 test_rpt_apis.py --env dev [--base-url URL] [--namespace RUN-x]
#                                [--approval-stub-url URL] [--log-file PATH]
#
# Exit code: 0 = every asserted call passed · 1 = an asserted failure ·
#            2 = refused to run (target not confirmed Dev/Test, inputs missing).
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
import time
import traceback
import urllib.parse
from pathlib import Path

try:
    import requests
    import yaml
except ImportError as exc:  # pragma: no cover
    print(f"api-verify: missing dependency ({exc}); pip install requests pyyaml", file=sys.stderr)
    sys.exit(2)

MODULE = "RPT"
SCRIPT = Path(__file__).resolve()
HTTP_METHODS = ("get", "post", "put", "patch", "delete")


# ═════════════════════════════════════════════════════════════════════════════
# config
# ═════════════════════════════════════════════════════════════════════════════
def find_repo_root() -> Path | None:
    for parent in SCRIPT.parents:
        if (parent / "scripts" / "gov-module.py").is_file():
            return parent
    return None


def load_plan(args) -> dict:
    """The v7 consumer contract, read through the one tool — never a typed path."""
    if args.plan_json:
        return json.loads(Path(args.plan_json).read_text())
    root = find_repo_root()
    if root is None:
        raise SystemExit("api-verify: scripts/gov-module.py not found above the script; pass --plan-json")
    out = subprocess.run(
        [sys.executable, str(root / "scripts" / "gov-module.py"), "--track", "backend", "plan", MODULE, "--json"],
        cwd=str(root), capture_output=True, text=True)
    if out.returncode != 0:
        raise SystemExit(f"api-verify: gov-module.py plan {MODULE} refused:\n{out.stderr or out.stdout}")
    return json.loads(out.stdout)


def build_arg_parser(extra_args):
    ap = argparse.ArgumentParser(description=f"api-verify — {MODULE} (Dev/Test only)")
    ap.add_argument("--base-url", default=None,
                    help="service base URL; default = the api-docs' first server")
    ap.add_argument("--env", required=True, choices=["dev", "test"],
                    help="the target environment class — the script refuses anything else")
    ap.add_argument("--namespace", default=None, help="run namespace for free values (default RUN-<UTC timestamp>)")
    ap.add_argument("--approval-stub-url", default=None,
                    help="Dev/Test stub of the host Approval API; without it no approval-enabled decision is exercised")
    ap.add_argument("--log-file", default=None, help="service log for approximate correlation (default logs/aias-local.log)")
    ap.add_argument("--check-timeout", type=float, default=120.0,
                    help="seconds to poll an asynchronous Check (aias.check.timeout, default PT2M)")
    ap.add_argument("--http-timeout", type=float, default=30.0)
    ap.add_argument("--report", default=None, help="problems report path (default <script dir>/<mod>_problems_report.md)")
    ap.add_argument("--plan-json", default=None, help="a saved `gov-module.py plan --json` output")
    for flags, kw in extra_args:
        ap.add_argument(*flags, **kw)
    return ap


def confirm_dev_test(base_url: str, env: str):
    host = (urllib.parse.urlparse(base_url).hostname or "").lower()
    if host in ("localhost", "127.0.0.1", "::1") or re.search(r"(^|[.-])(dev|test|local)(\d*)([.-]|$)", host):
        return True, f"host '{host}' accepted as a {env} target"
    return False, f"refusing {base_url}: host '{host}' cannot be confirmed as a Dev/Test target"


# ═════════════════════════════════════════════════════════════════════════════
# contract — the API document (OpenAPI 3.1) and a minimal schema validator
# ═════════════════════════════════════════════════════════════════════════════
class Contract:
    def __init__(self, spec_path: str):
        self.path = spec_path
        self.spec = yaml.safe_load(Path(spec_path).read_text())
        self.ops: dict[str, dict] = {}
        for path, item in (self.spec.get("paths") or {}).items():
            for method, op in item.items():
                if method in HTTP_METHODS and isinstance(op, dict):
                    self.ops[op.get("x-api-id")] = {"method": method.upper(), "path": path, "op": op}

    def op(self, api_id):
        return self.ops[api_id]

    def responses(self, api_id) -> dict:
        return self.ops[api_id]["op"].get("responses") or {}

    def success_status(self, api_id) -> int:
        return int(next(s for s in self.responses(api_id) if str(s).startswith("2")))

    def codes(self, api_id, status) -> list:
        return list((self.responses(api_id).get(str(status)) or {}).get("x-error-codes") or [])

    def response_schema(self, api_id, status, ctype):
        content = (self.responses(api_id).get(str(status)) or {}).get("content") or {}
        return (content.get(ctype) or {}).get("schema")

    def request_schema(self, api_id):
        body = self.ops[api_id]["op"].get("requestBody") or {}
        for ctype, c in (body.get("content") or {}).items():
            return ctype, self.resolve(c.get("schema") or {})
        return None, None

    def resolve(self, schema):
        seen = 0
        while isinstance(schema, dict) and "$ref" in schema and seen < 20:
            ref = schema["$ref"]
            node = self.spec
            for part in ref.lstrip("#/").split("/"):
                node = node[part]
            schema = node
            seen += 1
        return schema

    def top_fields(self, schema) -> set:
        schema = self.resolve(schema or {})
        if schema.get("type") == "array":
            schema = self.resolve(schema.get("items") or {})
        return set((schema.get("properties") or {}).keys())

    # -- validation ---------------------------------------------------------
    _PY = {"null": (type(None),), "string": (str,), "boolean": (bool,), "array": (list,), "object": (dict,),
           "integer": (int,), "number": (int, float)}

    def validate(self, schema, value, where="$") -> list:
        errs: list[str] = []
        self._v(self.resolve(schema or {}), value, where, errs)
        return errs

    def _v(self, schema, value, where, errs):
        schema = self.resolve(schema)
        if not isinstance(schema, dict) or not schema:
            return
        if "oneOf" in schema:
            matches = sum(1 for alt in schema["oneOf"] if not self.validate(alt, value, where))
            if matches != 1:
                errs.append(f"{where}: matches {matches} of the oneOf alternatives (expected exactly 1)")
            return
        types = schema.get("type")
        types = types if isinstance(types, list) else ([types] if types else [])
        if types:
            ok = False
            for t in types:
                py = self._PY.get(t, ())
                if isinstance(value, py) and not (t in ("integer", "number") and isinstance(value, bool)):
                    ok = True
                    break
            if not ok:
                errs.append(f"{where}: expected type {'|'.join(types)}, got {type(value).__name__}")
                return
        if value is None:
            return
        if "enum" in schema and value not in schema["enum"]:
            errs.append(f"{where}: value {value!r} not in enum {schema['enum']}")
        if isinstance(value, str):
            if "maxLength" in schema and len(value) > schema["maxLength"]:
                errs.append(f"{where}: length {len(value)} > maxLength {schema['maxLength']}")
            if "pattern" in schema and not re.search(schema["pattern"], value):
                errs.append(f"{where}: {value!r} does not match pattern {schema['pattern']}")
            if schema.get("format") == "date-time":
                try:
                    dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
                except ValueError:
                    errs.append(f"{where}: {value!r} is not a date-time")
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            if "minimum" in schema and value < schema["minimum"]:
                errs.append(f"{where}: {value} < minimum {schema['minimum']}")
        if isinstance(value, list):
            if "maxItems" in schema and len(value) > schema["maxItems"]:
                errs.append(f"{where}: {len(value)} items > maxItems {schema['maxItems']}")
            for i, item in enumerate(value):
                self._v(schema.get("items") or {}, item, f"{where}[{i}]", errs)
        if isinstance(value, dict):
            for req in schema.get("required") or []:
                if req not in value:
                    errs.append(f"{where}: required property '{req}' is missing")
            props = schema.get("properties") or {}
            for k, v in value.items():
                if k in props:
                    self._v(props[k], v, f"{where}.{k}", errs)
                elif schema.get("additionalProperties") is False:
                    errs.append(f"{where}: undeclared property '{k}'")


# ═════════════════════════════════════════════════════════════════════════════
# api-docs — the delivered surface (stage A inventory + pairing)
# ═════════════════════════════════════════════════════════════════════════════
def _table_after(body: str, heading_re: str) -> list[list[str]]:
    m = re.search(heading_re, body)
    if not m:
        return []
    rows, started = [], False
    for line in body[m.end():].splitlines():
        if line.startswith("|"):
            started = True
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):
                continue
            rows.append(cells)
        elif started and line.strip() == "":
            break
        elif started:
            break
        elif line.startswith("#"):
            break
    return rows[1:] if rows else []


def parse_api_docs(api_docs_dir: str):
    root = Path(api_docs_dir)
    servers, endpoints = [], []
    index = root / "index.md"
    if index.is_file():
        m = re.search(r"## Servers\s*\n+((?:- \S+\s*\n?)+)", index.read_text())
        servers = re.findall(r"- (\S+)", m.group(1)) if m else []
    for f in sorted((root / "endpoints").glob("*.md")) if (root / "endpoints").is_dir() else []:
        parts = re.split(r"(?m)^## (GET|POST|PUT|PATCH|DELETE) (\S+)\s*$", f.read_text())
        for i in range(1, len(parts), 3):
            method, path, body = parts[i], parts[i + 1], parts[i + 2]
            cid = re.search(r"Contract ID: `([^`]+)`", body)
            resp = re.findall(r"### Response `(\d{3})`", body)
            resp_fields = {r[0] for r in _table_after(body, r"### Response `\d{3}`[^\n]*\n") if r and "." not in r[0] and "[]" not in r[0]}
            req_fields = {r[0] for r in _table_after(body, r"### Request Body[^\n]*\n") if r and "." not in r[0] and "[]" not in r[0]}
            query = {r[0]: (r[2].lower() == "yes") for r in _table_after(body, r"### Query Parameters[^\n]*\n") if len(r) >= 3}
            endpoints.append({"method": method, "path": path, "contract_id": cid.group(1) if cid else None,
                              "responses": [int(x) for x in resp], "resp_fields": resp_fields,
                              "req_fields": req_fields, "query": query, "file": f.name})
    return servers, endpoints


def pair_surface(contract: Contract, endpoints: list):
    """Pair by method + path (§1); return (pairing rows, static contract-mismatch findings)."""
    rows, findings = [], []
    by_key = {(e["method"], e["path"]): e for e in endpoints}
    for api_id, o in sorted(contract.ops.items()):
        ep = by_key.get((o["method"], o["path"]))
        rows.append((api_id, o["method"], o["path"], ep["file"] if ep else "— not documented"))
        where = f"{o['method']} {o['path']}"
        if not ep:
            findings.append((api_id, where, "operation has no delivered counterpart in the api-docs (not yet served)"))
            continue
        if ep["contract_id"] != api_id:
            findings.append((api_id, where, f"api-docs carry contract id {ep['contract_id']!r}, the API document {api_id}"))
        success = contract.success_status(api_id)
        doc_success = [s for s in ep["responses"] if 200 <= s < 300]
        if doc_success and success not in doc_success:
            findings.append((api_id, where, f"api-docs document success status {doc_success}, the API document {success}"))
        spec_fields = contract.top_fields(contract.response_schema(api_id, success, "application/json"))
        if spec_fields and ep["resp_fields"] and spec_fields != ep["resp_fields"]:
            findings.append((api_id, where, "response fields differ — only in API document: "
                             f"{sorted(spec_fields - ep['resp_fields'])}; only in api-docs: {sorted(ep['resp_fields'] - spec_fields)}"))
        _, req = contract.request_schema(api_id)
        req_fields = set((req or {}).get("properties") or {})
        if req_fields and ep["req_fields"] and req_fields != ep["req_fields"]:
            findings.append((api_id, where, "request fields differ — only in API document: "
                             f"{sorted(req_fields - ep['req_fields'])}; only in api-docs: {sorted(ep['req_fields'] - req_fields)}"))
        for p in o["op"].get("parameters") or []:
            p = contract.resolve(p)
            if p.get("in") == "query" and p.get("name") in ep["query"] and bool(p.get("required")) != ep["query"][p["name"]]:
                findings.append((api_id, where, f"query parameter '{p['name']}': API document required={bool(p.get('required'))}, "
                                 f"api-docs required={ep['query'][p['name']]}"))
    spec_keys = {(o["method"], o["path"]) for o in contract.ops.values()}
    for e in endpoints:
        if (e["method"], e["path"]) not in spec_keys:
            rows.append((e["contract_id"] or "—", e["method"], e["path"], e["file"] + " (no API-document operation)"))
            findings.append((e["contract_id"] or "—", f"{e['method']} {e['path']}",
                             "delivered endpoint has no operation in the API document"))
    return rows, findings


# ═════════════════════════════════════════════════════════════════════════════
# client
# ═════════════════════════════════════════════════════════════════════════════
class Call:
    def __init__(self, method, url, request_desc, response=None, error=None, log_offset=0):
        self.method, self.url, self.request_desc, self.error, self.log_offset = method, url, request_desc, error, log_offset
        self.status = response.status_code if response is not None else None
        self.headers = dict(response.headers) if response is not None else {}
        self.ctype = (self.headers.get("Content-Type") or "").split(";")[0].strip().lower()
        self.body = None
        self.text = ""
        if response is not None:
            self.text = response.text[:4000]
            try:
                self.body = response.json()
            except ValueError:
                self.body = None

    @property
    def code(self):
        return self.body.get("code") if isinstance(self.body, dict) else None

    def safe_body(self):
        """ProblemDetail bodies verbatim; success bodies as a shape summary (no document content, G13)."""
        if self.ctype == "application/problem+json" and isinstance(self.body, dict):
            return json.dumps(self.body, ensure_ascii=False)
        if isinstance(self.body, list):
            return f"array[{len(self.body)}]" + (f" of objects with keys {sorted(self.body[0].keys())}" if self.body and isinstance(self.body[0], dict) else "")
        if isinstance(self.body, dict):
            return "object with keys " + json.dumps(sorted(self.body.keys()))
        return (self.text or "")[:300]


class Client:
    def __init__(self, base_url, http_timeout, log_file):
        self.base = base_url.rstrip("/")
        self.session = requests.Session()
        self.timeout = http_timeout
        self.log_file = Path(log_file) if log_file else None

    def log_offset(self):
        try:
            return self.log_file.stat().st_size if self.log_file else 0
        except OSError:
            return 0

    def request(self, method, path, *, params=None, json_body=None, raw=None, files=None, data=None, headers=None):
        assert method in ("GET", "POST"), "aias exposes no PUT / PATCH / DELETE — the script never calls one"
        url = self.base + path
        if params:
            url_shown = url + "?" + urllib.parse.urlencode(params)
        else:
            url_shown = url
        desc = {}
        if json_body is not None:
            desc["json"] = json_body
        if raw is not None:
            desc["raw"] = raw if isinstance(raw, str) else f"<{len(raw)} bytes>"
            if headers:
                desc["headers"] = headers
        if files:
            desc["multipart"] = {k: (f"<file {v[0]!r}, {len(v[1])} bytes synthetic>" if isinstance(v, tuple) else v)
                                 for k, v in files.items()}
            if data:
                desc["multipart"].update(data)
        off = self.log_offset()
        try:
            resp = self.session.request(method, url, params=params, json=json_body,
                                        data=raw if raw is not None else data, files=files,
                                        headers=headers, timeout=self.timeout)
            return Call(method, url_shown, desc, resp, None, off)
        except requests.RequestException as exc:
            return Call(method, url_shown, desc, None, f"{type(exc).__name__}: {exc}", off)

    def get(self, path, **kw):
        return self.request("GET", path, **kw)

    def post(self, path, **kw):
        return self.request("POST", path, **kw)

    def log_excerpt(self, call: Call, needle=None, limit=12):
        if not self.log_file:
            return [], True
        try:
            with self.log_file.open("rb") as fh:
                fh.seek(call.log_offset)
                chunk = fh.read(200_000).decode("utf-8", "replace")
        except OSError:
            return [], True
        lines = [l[:300] for l in chunk.splitlines() if re.search(r"\b(WARN|ERROR)\b|Exception", l)]
        exact = bool(needle) and any(str(needle) in l for l in lines)
        return lines[:limit], not exact


# ═════════════════════════════════════════════════════════════════════════════
# results
# ═════════════════════════════════════════════════════════════════════════════
BUCKETS = ("contract mismatch", "likely real bug", "test assumption mismatch", "infrastructure")


class Runner:
    def __init__(self, contract: Contract, client: Client, namespace: str):
        self.c, self.http, self.ns = contract, client, namespace
        self.suite = "preflight"
        self.results: list[dict] = []        # asserted
        self.observations: list[dict] = []   # stage E — never pass/fail
        self.blocked: list[dict] = []        # A0 — blocked on precondition
        self.not_exercisable: list[dict] = []
        self.untraced: list[dict] = []
        self.preflight: list[dict] = []
        self.surviving: list[dict] = []
        self.static: list[tuple] = []
        self.pairing: list[tuple] = []
        self.crash = None

    # -- bookkeeping --------------------------------------------------------
    def begin(self, suite):
        self.suite = suite
        print(f"\n▶ {suite}")

    def _add(self, name, covers, ok, expected, call: Call | None, bucket=None, taxonomy=None, actual=None, note=None,
             log_needle=None):
        actual = actual if actual is not None else (
            (f"transport error {call.error}" if call and call.error else
             f"HTTP {call.status} {call.ctype} code={call.code}") if call else "—")
        res = {"suite": self.suite, "name": name, "covers": covers, "ok": ok, "expected": expected, "actual": actual,
               "bucket": None if ok else bucket, "taxonomy": None if ok else taxonomy, "note": note,
               "call": None, "log": [], "log_approx": True}
        if call is not None:
            res["call"] = {"method": call.method, "url": call.url, "request": call.request_desc,
                           "status": call.status, "body": call.safe_body() if not call.error else call.error}
            if not ok and taxonomy != "CONTRACT_BREAK":
                res["log"], res["log_approx"] = self.http.log_excerpt(call, log_needle)
        self.results.append(res)
        print(f"  {'PASS' if ok else 'FAIL'}  {name}" + ("" if ok else f"  [{taxonomy}] expected {expected}; got {actual}"))
        return ok

    def observe(self, name, covers, call: Call, note):
        self.observations.append({"suite": self.suite, "name": name, "covers": covers, "note": note,
                                  "status": call.status, "code": call.code, "ctype": call.ctype,
                                  "url": call.url, "request": call.request_desc, "error": call.error,
                                  "body": call.safe_body() if not call.error else call.error, "log": [], "log_approx": True})
        if call.status and call.status >= 500:   # an unexplained 5xx is surfaced as a likely real bug (stage G)
            self.observations[-1]["log"], self.observations[-1]["log_approx"] = self.http.log_excerpt(call)
        print(f"  OBS   {name}: HTTP {call.status} code={call.code}")

    def block(self, item, covers, reason):
        self.blocked.append({"suite": self.suite, "item": item, "covers": covers, "reason": reason})
        print(f"  BLOCKED {item} — {reason}")

    def unexercisable(self, api_id, code, reason, tc=""):
        self.not_exercisable.append({"api": api_id, "code": code, "reason": reason, "tc": tc})

    def untraced_negative(self, api_id, code):
        self.untraced.append({"api": api_id, "code": code})

    def precondition(self, value, source, check, ok, detail, blocks):
        self.preflight.append({"value": value, "source": source, "check": check, "ok": ok, "detail": detail, "blocks": blocks})
        print(f"  {'OK  ' if ok else 'MISS'}  precondition {value!r} ({source}) — {'verified' if ok else detail}")
        return ok

    def track(self, resource, ident, service_code, request_number, what):
        self.surviving.append({"resource": resource, "id": ident, "service_code": service_code,
                               "request_number": request_number, "what": what})

    def asserted_failures(self):
        return [r for r in self.results if not r["ok"]]

    # -- assertions ---------------------------------------------------------
    def _transport(self, name, covers, call):
        return self._add(name, covers, False, "a response", call, "infrastructure", "ENVIRONMENT_FAILURE")

    def expect_success(self, name, api_id, call: Call, covers="", checks=()):
        """Assert the documented success status and the response schema; `checks` = [(label, bool, detail)]."""
        covers = covers or api_id
        if call.error:
            return self._transport(name, covers, call), None
        status = self.c.success_status(api_id)
        if call.status != status:
            if call.status and call.status >= 500:
                bucket, tax = "likely real bug", "SERVER_ERROR"
            elif call.status == 404 and call.code is None:
                bucket, tax = "contract mismatch", "MISSING_IMPLEMENTATION"
            elif call.status and 200 <= call.status < 300:
                bucket, tax = "contract mismatch", "CONTRACT_BREAK"
            else:
                bucket, tax = "likely real bug", "VALIDATION_FAILURE"
            self._add(f"{name} — HTTP {status}", covers, False, f"HTTP {status}", call, bucket, tax)
            return False, None
        ok_all = self._add(f"{name} — HTTP {status}", covers, True, f"HTTP {status}", call)
        schema = self.c.response_schema(api_id, status, "application/json")
        errs = [] if call.ctype == "application/json" else [f"Content-Type {call.ctype!r}, API document application/json"]
        if schema is not None:
            errs += self.c.validate(schema, call.body) if call.body is not None or call.ctype == "application/json" else ["no JSON body"]
        ok_all &= self._add(f"{name} — body conforms to the API document", covers, not errs,
                            "the API document's response schema", call, "contract mismatch", "CONTRACT_BREAK",
                            actual="; ".join(errs[:6]) if errs else None)
        for label, ok, detail in checks:
            ok_all &= self._add(f"{name} — {label}", covers, bool(ok), label, call, "likely real bug",
                                "BUSINESS_LOGIC_ISSUE", actual=None if ok else detail)
        return ok_all, call.body

    def expect_problem(self, name, api_id, call: Call, status: int, code: str, covers=""):
        """Stage C: assert HTTP status + ProblemDetail code (never message text), then the ProblemDetail schema."""
        if code not in self.c.codes(api_id, status):
            raise AssertionError(f"generation error: {code} is not an x-error-code of {api_id} {status}")
        covers = covers or f"{api_id} ; {code}"
        if call.error:
            return self._transport(name, covers, call)
        if call.status == status and call.code == code:
            ok = self._add(f"{name} — HTTP {status} {code}", covers, True, f"HTTP {status} code={code}", call)
            schema = self.c.response_schema(api_id, status, "application/problem+json")
            errs = [] if call.ctype == "application/problem+json" else [f"Content-Type {call.ctype!r}, API document application/problem+json"]
            if schema is not None:
                errs += self.c.validate(schema, call.body)
            ok &= self._add(f"{name} — ProblemDetail conforms to the API document", covers, not errs,
                            "ProblemDetail {type, title, status, code} (+detail)", call, "contract mismatch",
                            "CONTRACT_BREAK", actual="; ".join(errs[:6]) if errs else None)
            return ok
        documented = [int(s) for s in self.c.responses(api_id) if str(s)[0] in "45"]
        if call.status and call.status >= 500:
            bucket, tax = "likely real bug", "SERVER_ERROR"
        elif call.status and 200 <= call.status < 300:
            bucket, tax = "likely real bug", "BUSINESS_LOGIC_ISSUE"     # a documented rejection did not happen
        elif call.status == 404 and call.code is None:
            bucket, tax = "contract mismatch", "MISSING_IMPLEMENTATION"
        elif call.status not in documented:
            bucket, tax = "test assumption mismatch", "CONTRACT_BREAK"   # rejected with an undocumented status
        else:
            bucket, tax = "likely real bug", "BUSINESS_LOGIC_ISSUE"
        return self._add(f"{name} — HTTP {status} {code}", covers, False, f"HTTP {status} code={code}", call, bucket, tax)


def poll_until(read, end_states, timeout, state_of=lambda b: (b or {}).get("status")):
    """Poll a documented read until a documented end state or the per-check timeout — never a fixed sleep."""
    deadline, wait, last = time.monotonic() + timeout, 0.25, None
    while True:
        last = read()
        if last.error is None and last.status == 200 and state_of(last.body) in end_states:
            return last, True
        if time.monotonic() >= deadline:
            return last, False
        time.sleep(min(wait, max(0.0, deadline - time.monotonic())))
        wait = min(wait * 2, 3.0)


# ═════════════════════════════════════════════════════════════════════════════
# report
# ═════════════════════════════════════════════════════════════════════════════
def _md(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def write_report(path: Path, r: Runner, meta: dict, exit_code: int):
    fails = r.asserted_failures()
    L = []
    L.append(f"# {MODULE} — API verification problems report")
    L.append("")
    L.append(f"_Generated by `{SCRIPT.name}` (api-verify skill). Dev/Test only. Run namespace `{r.ns}`._")
    L.append("")
    L.append("## Run")
    L.append("")
    for k, v in meta.items():
        L.append(f"- **{k}**: {v}")
    L.append(f"- **Result**: {'PASS' if exit_code == 0 else 'FAIL'} (exit {exit_code}) — "
             f"{len(r.results) - len(fails)} asserted checks passed, {len(fails)} failed; "
             f"{len(r.observations)} observations; {len(r.blocked)} blocked on precondition; "
             f"{len(r.not_exercisable)} not exercisable")
    if r.crash:
        L.append(f"- **Script crash** (TEST_STRUCTURE_FAILURE): `{_md(r.crash.splitlines()[-1])}`")
    L.append("")

    L.append("## Preconditions (stage A0)")
    L.append("")
    if r.preflight:
        L.append("| Value | Supplied by | Verified through | Result | Blocks |")
        L.append("|---|---|---|---|---|")
        for p in r.preflight:
            L.append(f"| `{_md(p['value'])}` | {_md(p['source'])} | {_md(p['check'])} | "
                     f"{'verified' if p['ok'] else 'NOT MET — ' + _md(p['detail'])} | {_md(p['blocks'])} |")
    else:
        L.append("No externally-owned value is referenced.")
    L.append("")

    L.append("## Inventory and pairing (stage A)")
    L.append("")
    L.append("| API id | Method | Path | api-docs |")
    L.append("|---|---|---|---|")
    for row in r.pairing:
        L.append("| " + " | ".join(_md(x) for x in row) + " |")
    L.append("")

    L.append("## Problems")
    L.append("")
    if not fails and not r.static and not r.crash and not any(o["status"] and o["status"] >= 500 for o in r.observations):
        L.append("No failure.")
    for bucket in BUCKETS:
        items = [f for f in fails if f["bucket"] == bucket]
        static = r.static if bucket == "contract mismatch" else []
        obs5 = [o for o in r.observations if o["status"] and o["status"] >= 500] if bucket == "likely real bug" else []
        if not items and not static and not obs5:
            continue
        L.append(f"### {bucket.capitalize()}")
        L.append("")
        for f in items:
            c = f["call"] or {}
            L.append(f"- **[{f['taxonomy']}] {_md(f['name'])}** — `{_md(f['covers'])}` (suite `{f['suite']}`)")
            if c:
                L.append(f"  - Request: `{c['method']} {_md(c['url'])}`" + (f" body `{_md(json.dumps(c['request'], ensure_ascii=False))}`" if c.get("request") else ""))
            L.append(f"  - Expected: {_md(f['expected'])}")
            L.append(f"  - Actual: {_md(f['actual'])}")
            if c and c.get("body"):
                L.append(f"  - Response: `{_md(c['body'])[:600]}`")
            if f["log"]:
                L.append(f"  - Log ({'approximate' if f['log_approx'] else 'correlated'}):")
                L.append("    ```")
                L.extend("    " + ln for ln in f["log"])
                L.append("    ```")
        if bucket == "likely real bug":
            for o in [o for o in r.observations if o["status"] and o["status"] >= 500]:
                L.append(f"- **[SERVER_ERROR] {_md(o['name'])}** — `{_md(o['covers'])}` (suite `{o['suite']}`; observed in "
                         "stage E — not asserted, does not affect the exit code)")
                L.append(f"  - Request: `{_md(o['url'])}` `{_md(json.dumps(o['request'], ensure_ascii=False))}`")
                L.append(f"  - Expected: a 4xx refusal (no documented outcome; {_md(o['note'])})")
                L.append(f"  - Actual: HTTP {o['status']} code={o['code']}")
                L.append(f"  - Response: `{_md(o['body'])[:600]}`")
                if o["log"]:
                    L.append(f"  - Log ({'approximate' if o['log_approx'] else 'correlated'}):")
                    L.append("    ```")
                    L.extend("    " + ln for ln in o["log"])
                    L.append("    ```")
        if static:
            L.append("- **Static (api-docs vs API document — not runtime-asserted, does not affect the exit code):**")
            for api_id, where, what in static:
                L.append(f"  - [CONTRACT_BREAK] `{api_id}` `{where}` — {_md(what)}")
        L.append("")
    if r.crash:
        L.append("### Script failure")
        L.append("")
        L.append("```")
        L.append(r.crash[-3000:])
        L.append("```")
        L.append("")

    L.append("## Blocked on precondition")
    L.append("")
    if r.blocked:
        L.append("| Suite | Item | Covers | Reason |")
        L.append("|---|---|---|---|")
        for b in r.blocked:
            L.append(f"| {b['suite']} | {_md(b['item'])} | {_md(b['covers'])} | {_md(b['reason'])} |")
    else:
        L.append("None.")
    L.append("")

    L.append("## Not exercisable")
    L.append("")
    if r.not_exercisable:
        L.append("| API id | Code | TC | Reason |")
        L.append("|---|---|---|---|")
        for n in r.not_exercisable:
            L.append(f"| {n['api']} | `{n['code']}` | {n['tc'] or '—'} | {_md(n['reason'])} |")
    else:
        L.append("None.")
    L.append("")

    L.append("## Untraced negatives")
    L.append("")
    L.append("Asserted negatives with no TC in the test plan naming the same operation and code (tagged with the code only).")
    L.append("")
    if r.untraced:
        for u in r.untraced:
            L.append(f"- `{u['api']}` · `{u['code']}`")
    else:
        L.append("None.")
    L.append("")

    L.append("## Observations (stage E — never pass/fail)")
    L.append("")
    if r.observations:
        L.append("| Suite | Scenario | Covers | Request | Observed | Note |")
        L.append("|---|---|---|---|---|---|")
        for o in r.observations:
            obs = o["error"] or f"HTTP {o['status']} {o['ctype']} code={o['code']}"
            L.append(f"| {o['suite']} | {_md(o['name'])} | {_md(o['covers'])} | `{_md(o['url'])}` | {_md(obs)} | {_md(o['note'])} |")
    else:
        L.append("None.")
    L.append("")

    L.append("## Suites")
    L.append("")
    suites = []
    for res in r.results:
        if res["suite"] not in suites:
            suites.append(res["suite"])
    for s in suites:
        rs = [x for x in r.results if x["suite"] == s]
        L.append(f"### {s} — {sum(x['ok'] for x in rs)}/{len(rs)} passed")
        L.append("")
        L.append("| Result | Check | Covers |")
        L.append("|---|---|---|")
        for x in rs:
            L.append(f"| {'PASS' if x['ok'] else 'FAIL'} | {_md(x['name'])} | {_md(x['covers'])} |")
        L.append("")

    L.append("## Surviving records")
    L.append("")
    if r.surviving:
        L.append("aias exposes no update or delete operation; these records remain in the Dev/Test schema until the "
                 "service's own retention purge removes them. A purge is a human's decision — none was executed.")
        L.append("")
        L.append("| Resource | Id | Service code | Request number | Created by |")
        L.append("|---|---|---|---|---|")
        for s in r.surviving:
            L.append(f"| {s['resource']} | {s['id']} | `{_md(s['service_code'])}` | `{_md(s['request_number'])}` | {_md(s['what'])} |")
    else:
        L.append("The tracked-id set is empty: no call of this run created a record.")
    L.append("")
    path.write_text("\n".join(L) + "\n")


# ═════════════════════════════════════════════════════════════════════════════
# main
# ═════════════════════════════════════════════════════════════════════════════
def run(extra_args, preflight, suites):
    args = build_arg_parser(extra_args).parse_args()
    plan = load_plan(args)
    for key in ("api_spec", "api_docs", "test_plan", "delivered_version", "state_file"):
        if not plan.get(key):
            print(f"api-verify: plan.{key} missing — STOP", file=sys.stderr)
            return 2
    if not Path(plan["api_spec"]).is_file():
        print("api-verify: no API document (plan.api_spec) — there is no contract to hold the docs to. STOP", file=sys.stderr)
        return 2
    if not (Path(plan["api_docs"]) / "index.md").is_file():
        print("api-verify: no generated api-docs (index.md) — run /generate-api-docs first. STOP", file=sys.stderr)
        return 2
    contract = Contract(plan["api_spec"])
    servers, endpoints = parse_api_docs(plan["api_docs"])
    base_url = args.base_url or (servers[0] if servers else "http://localhost:7271")
    ok, why = confirm_dev_test(base_url, args.env)
    print(f"api-verify {MODULE} · {why}")
    if not ok:
        print(f"api-verify: {why}", file=sys.stderr)
        return 2
    root = find_repo_root()
    log_file = args.log_file or (str(root / "logs" / "aias-local.log") if root and (root / "logs" / "aias-local.log").is_file() else None)
    namespace = args.namespace or "RUN-" + dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    report = Path(args.report) if args.report else SCRIPT.parent / f"{MODULE.lower()}_problems_report.md"
    catalog = Path(plan.get("exec_packages") or "") / "_SECTIONS.md"
    r = Runner(contract, Client(base_url, args.http_timeout, log_file), namespace)
    r.pairing, r.static = pair_surface(contract, endpoints)
    started = dt.datetime.now().astimezone().isoformat(timespec="seconds")
    meta = {
        "Module / delivered version": f"{MODULE} v{plan['delivered_version']}",
        "Target": f"{base_url} (--env {args.env})",
        "Started": started,
        "API document": f"`{plan['api_spec']}`",
        "api-docs": f"`{plan['api_docs']}` ({len(endpoints)} endpoints)",
        "Test plan": f"`{plan['test_plan']}`",
        "Error catalog": f"`{catalog}` (error-catalog block)",
        "Approval stub": args.approval_stub_url or "none given — no approval-enabled decision is exercised",
        "Log correlation": f"`{log_file}`" if log_file else "no log file",
    }
    print("inputs: " + "; ".join(f"{k}={v}" for k, v in meta.items()))
    exit_code = 1
    try:
        r.begin("preflight")
        ctx = preflight(r, args, contract)
        for suite in suites:
            r.begin(suite.__name__)
            suite(r, ctx)
    except Exception:  # the report is still written (finally)
        r.crash = traceback.format_exc()
        print(r.crash, file=sys.stderr)
    finally:
        exit_code = 0 if not r.asserted_failures() and not r.crash else 1
        meta["Ended"] = dt.datetime.now().astimezone().isoformat(timespec="seconds")
        write_report(report, r, meta, exit_code)
        fails = r.asserted_failures()
        print(f"\n{MODULE}: {'PASS' if exit_code == 0 else 'FAIL'} — {len(r.results) - len(fails)} passed, "
              f"{len(fails)} failed, {len(r.observations)} observations, {len(r.blocked)} blocked, "
              f"{len(r.not_exercisable)} not exercisable, {len(r.surviving)} surviving records → {report}")
    return exit_code


# ═════════════════════════════════════════════════════════════════════════════
# module-specific suites (stage B order)
# ═════════════════════════════════════════════════════════════════════════════

# ═════════════════════════════════════════════════════════════════════════════
# helpers — ids threaded from the producing call's own return value
# ═════════════════════════════════════════════════════════════════════════════
_OWNER_CONTRACTS: dict[str, Contract] = {}


def owner_contract(r: Runner, api_id: str) -> Contract:
    """The API document that owns an operation id (another module's, read through gov-module.py)."""
    owner = api_id.split("-")[1]
    if owner == MODULE:
        return r.c
    if owner not in _OWNER_CONTRACTS:
        root = find_repo_root()
        out = subprocess.run([sys.executable, str(root / "scripts" / "gov-module.py"), "--track", "backend",
                              "plan", owner, "--json"], cwd=str(root), capture_output=True, text=True)
        if out.returncode != 0:
            raise RuntimeError(f"gov-module.py plan {owner} refused: {out.stderr or out.stdout}")
        _OWNER_CONTRACTS[owner] = Contract(json.loads(out.stdout)["api_spec"])
    return _OWNER_CONTRACTS[owner]


def path_of(r: Runner, api_id: str, **params) -> str:
    path = owner_contract(r, api_id).op(api_id)["path"]
    for key, value in params.items():
        path = path.replace("{" + key + "}", urllib.parse.quote(str(value), safe=""))
    return path


def available_services(r: Runner):
    """API-REG-001 — the registry's documented list (externally-owned service codes)."""
    call = r.http.get(path_of(r, "API-REG-001"))
    if call.error or call.status != 200 or not isinstance(call.body, list):
        return None, call
    return [s for s in call.body if isinstance(s, dict) and s.get("available") is True], call


def precheck_services(r: Runner, services, call, want: str, blocks: str):
    if services is None:
        return r.precondition(want, "registry (REG)", "API-REG-001 GET /api/v1/services", False,
                              f"registry read failed: HTTP {call.status} {call.error or call.code}", blocks)
    return None


def absent_check(r: Runner, check_id, source: str, blocks: str) -> bool:
    """A test-plan 'unknown Check' value is verified absent through API-RPT-001 before it is used."""
    call = r.http.get(path_of(r, "API-RPT-001", checkId=check_id))
    ok = call.status == 404 and call.code == "RPT-404-CHECK-NOT-FOUND"
    r.precondition(check_id, source, "API-RPT-001 GET /api/v1/checks/{checkId} → 404", ok,
                   "absent" if ok else f"HTTP {call.status} code={call.code} — exists or the read failed", blocks)
    return ok


def start_check(r: Runner, service: dict, employee_id: str, label: str):
    """API-INT-001 — the documented create; the Check it creates is tracked as a surviving record."""
    request_number = f"{r.ns}-{label}"
    body = {"serviceCode": service["serviceCode"], "requestNumber": request_number, "employeeId": employee_id}
    call = r.http.post(path_of(r, "API-INT-001"), json_body=body)
    if call.status == 202 and isinstance(call.body, dict) and call.body.get("checkId") is not None:
        r.track("Check", call.body["checkId"], service["serviceCode"], request_number,
                f"API-INT-001 start ({label}, fetch mode {service.get('fetchMode')})")
    return call, request_number


def upload(r: Runner, check_id, document_type, content: bytes | None = None, file_name: str | None = None,
           service_code="", request_number=""):
    """API-INT-002 — one small synthetic file (G13); a created upload is tracked."""
    content = content if content is not None else f"SYNTHETIC api-verify document {r.ns}\n".encode()
    file_name = file_name or f"{r.ns}-synthetic.txt"
    call = r.http.post(path_of(r, "API-INT-002", checkId=check_id),
                       files={"file": (file_name, content, "text/plain")}, data={"documentType": document_type})
    if call.status == 201 and isinstance(call.body, dict) and call.body.get("uploadedDocumentId") is not None:
        r.track("Uploaded Document", call.body["uploadedDocumentId"], service_code, request_number,
                f"API-INT-002 upload of {document_type} to Check {check_id}")
    return call


def read_check(r: Runner, check_id):
    return r.http.get(path_of(r, "API-RPT-001", checkId=check_id))


def wait_until_ended(r: Runner, check_id, timeout):
    return poll_until(lambda: read_check(r, check_id), {"COMPLETED", "FAILED"}, timeout)


OVERFLOW_ID = "9" * 20   # larger than int64 — exploratory only (observation)

# RPT — Report Store: API-RPT-001 … API-RPT-003 (read-only; the result port and the Employee Decision are
# in-process, ADR-RPT-006 — a Check is created over HTTP only through Host Integration's API-INT-001).
# Stage-B order: registry read → start a Check (API-INT-001) → read it → poll to its end → read again →
# list the Checks of its request → decision agreement of its service.

EXTRA_ARGS = [
    (["--unknown-check-id"], {"type": int, "default": 998, "help": "an absent Check identifier (TC-RPT-030 test data)"}),
    (["--employee-id"], {"default": "E-3307", "help": "employeeId sent on a start (TC-INT-025/026 test data)"}),
]

LIST_REQUEST_NUMBER = "1001"   # TC-RPT-035 test data


def preflight(r: Runner, args, c: Contract):
    """Covers: A0 — an available service to start a Check of."""
    services, call = available_services(r)
    precheck_services(r, services, call, "the registry's services", "API-RPT-001/002 happy paths")
    chosen = (services or [None])[0]
    r.precondition("an available service", "API-RPT-001 / API-RPT-002 happy paths — a Check is created only "
                   "through API-INT-001", "API-REG-001 GET /api/v1/services", chosen is not None,
                   "the registry holds no service — package directory empty",
                   "read a Check (TC-RPT-027/028/031), list the Checks of its request (TC-RPT-033)")
    r.precondition(args.unknown_check_id, "TC-RPT-030 test data (no Check run 998)",
                   "asserted by TC-RPT-030 itself (API-RPT-001 is the read that would show it)", True, "", "TC-RPT-030")
    for api_id in ("API-RPT-001", "API-RPT-002", "API-RPT-003"):
        r.unexercisable(api_id, "RPT-500", "an unexpected server failure cannot be produced through documented "
                                           "endpoints or Dev/Test fixtures")
    return {"service": chosen, "unknown": args.unknown_check_id, "employee": args.employee_id,
            "timeout": args.check_timeout, "check": None}


def test_checks(r: Runner, ctx):
    """Covers: API-RPT-001, API-RPT-002 ; Negative: PLATFORM-STD / RPT-400-CHECK-ID-INVALID ;
    PLATFORM-STD / RPT-404-CHECK-NOT-FOUND / TC-RPT-030 ; RULE-RPT-009 / RPT-400-REQUEST-KEYS-MISSING / TC-RPT-035"""
    svc = ctx["service"]
    if svc is None:
        for item, tc in (("read a running Check — no report yet", "API-RPT-001 ; TC-RPT-027"),
                         ("read an ended Check — report or failure reason", "API-RPT-001 ; TC-RPT-028 / TC-RPT-031"),
                         ("list the Checks of a request — the created Check", "API-RPT-002 ; TC-RPT-033")):
            r.block(item, tc, "no available service in the registry (package directory empty) — no Check can be "
                              "started through API-INT-001")
    else:
        call, rn = start_check(r, svc, ctx["employee"], "rpt")
        if call.status != 202 or not isinstance(call.body, dict):
            r.block("read a Check", "API-RPT-001", f"DEPENDENCY_FAILURE — setup API-INT-001 answered HTTP {call.status} "
                                                   f"code={call.code}")
        else:
            cid = call.body["checkId"]
            ctx["check"] = (cid, svc["serviceCode"], rn)
            c0 = read_check(r, cid)
            r.expect_success("read the new Check", "API-RPT-001", c0, "API-RPT-001 ; TC-RPT-027", checks=[
                ("identifiers exactly as sent", isinstance(c0.body, dict) and c0.body.get("checkId") == cid
                 and c0.body.get("serviceCode") == svc["serviceCode"] and c0.body.get("requestNumber") == rn
                 and c0.body.get("employeeId") == ctx["employee"], c0.safe_body())])
            last, ended = wait_until_ended(r, cid, ctx["timeout"])
            if not ended:
                r.block("read an ended Check", "API-RPT-001 ; TC-RPT-028 / TC-RPT-031",
                        f"the Check did not end within {ctx['timeout']}s (status "
                        f"{(last.body or {}).get('status') if isinstance(last.body, dict) else last.error})")
            else:
                b = last.body
                r.expect_success("read the ended Check", "API-RPT-001", last, "API-RPT-001 ; TC-RPT-028 / TC-RPT-031", checks=[
                    ("COMPLETED carries an Overall Status; FAILED a failure reason",
                     (b.get("status") == "COMPLETED" and b.get("overallStatus") is not None) or
                     (b.get("status") == "FAILED" and b.get("failureReason") is not None),
                     f"status={b.get('status')} overallStatus={b.get('overallStatus')} failureReason={b.get('failureReason')}")])
            lst = r.http.get(path_of(r, "API-RPT-002"), params={"serviceCode": svc["serviceCode"], "requestNumber": rn})
            r.expect_success("list the Checks of the run's request", "API-RPT-002", lst, "API-RPT-002 ; TC-RPT-033", checks=[
                ("total 1 and the created Check listed", isinstance(lst.body, dict) and lst.body.get("total") == 1
                 and [x.get("checkId") for x in lst.body.get("checks", [])] == [cid], lst.safe_body())])

    # a request no Check was made for: the run's own namespace
    keys = {"serviceCode": f"{r.ns}-SVC-A", "requestNumber": f"{r.ns}-REQ"}   # placeholders ⟨SVC-A⟩ (TC-RPT-033)
    lst = r.http.get(path_of(r, "API-RPT-002"), params=keys)
    r.expect_success("list the Checks of a request with none", "API-RPT-002", lst, "API-RPT-002 ; TC-RPT-033 (shape)", checks=[
        ("total 0, no Check", isinstance(lst.body, dict) and lst.body.get("total") == 0 and lst.body.get("checks") == [],
         lst.safe_body())])

    # stage C
    r.expect_problem("checkId not a number", "API-RPT-001", r.http.get(path_of(r, "API-RPT-001", checkId="abc")), 400,
                     "RPT-400-CHECK-ID-INVALID", "API-RPT-001 ; PLATFORM-STD / RPT-400-CHECK-ID-INVALID")
    r.untraced_negative("API-RPT-001", "RPT-400-CHECK-ID-INVALID")
    r.expect_problem("unknown Check", "API-RPT-001", read_check(r, ctx["unknown"]), 404, "RPT-404-CHECK-NOT-FOUND",
                     "API-RPT-001 ; PLATFORM-STD / RPT-404-CHECK-NOT-FOUND / TC-RPT-030")
    lp = path_of(r, "API-RPT-002")
    tag = "API-RPT-002 ; RULE-RPT-009 / RPT-400-REQUEST-KEYS-MISSING / TC-RPT-035"
    r.expect_problem("list without a service code", "API-RPT-002",
                     r.http.get(lp, params={"requestNumber": LIST_REQUEST_NUMBER}), 400, "RPT-400-REQUEST-KEYS-MISSING", tag)
    r.expect_problem("list without a request number", "API-RPT-002",
                     r.http.get(lp, params={"serviceCode": keys["serviceCode"]}), 400, "RPT-400-REQUEST-KEYS-MISSING", tag)
    r.expect_problem("list with a blank service code", "API-RPT-002",
                     r.http.get(lp, params={"serviceCode": " ", "requestNumber": LIST_REQUEST_NUMBER}), 400,
                     "RPT-400-REQUEST-KEYS-MISSING", tag)
    r.expect_problem("list with a blank request number", "API-RPT-002",
                     r.http.get(lp, params={"serviceCode": keys["serviceCode"], "requestNumber": " "}), 400,
                     "RPT-400-REQUEST-KEYS-MISSING", tag)

    # stage E
    r.observe("checkId larger than int64", "API-RPT-001 ; format int64",
              read_check(r, OVERFLOW_ID), "no documented outcome for an out-of-range number")
    r.observe("service code of 101 characters", "API-RPT-002 ; maxLength 100",
              r.http.get(lp, params={"serviceCode": "a" * 101, "requestNumber": keys["requestNumber"]}),
              "the API document states no outcome for an over-length key")


def test_decision_agreement(r: Runner, ctx):
    """Covers: API-RPT-003 ; Negative: RULE-RPT-015 / RPT-400-SERVICE-CODE-MISSING / TC-RPT-049"""
    p = path_of(r, "API-RPT-003")
    none = r.http.get(p, params={"serviceCode": f"{r.ns}-SVC-B"})          # placeholder ⟨SVC-B⟩ (TC-RPT-048)
    r.expect_success("agreement of a service with no decision", "API-RPT-003", none, "API-RPT-003 ; TC-RPT-048", checks=[
        ("empty array", none.body == [], none.safe_body())])
    if ctx["service"] is not None:
        real = r.http.get(p, params={"serviceCode": ctx["service"]["serviceCode"]})
        r.expect_success("agreement of a registered service", "API-RPT-003", real, "API-RPT-003 ; TC-RPT-047 (shape)")
    else:
        r.block("agreement counted per version for a decided service", "API-RPT-003 ; TC-RPT-047",
                "no service and no decided Check — a decision is recorded only through API-INT-004 on a COMPLETED Check")
    tag = "API-RPT-003 ; RULE-RPT-015 / RPT-400-SERVICE-CODE-MISSING / TC-RPT-049"
    r.expect_problem("agreement without a service code", "API-RPT-003", r.http.get(p), 400, "RPT-400-SERVICE-CODE-MISSING", tag)
    r.expect_problem("agreement with a blank service code", "API-RPT-003", r.http.get(p, params={"serviceCode": " "}), 400,
                     "RPT-400-SERVICE-CODE-MISSING", tag)
    r.observe("service code of 101 characters", "API-RPT-003 ; maxLength 100",
              r.http.get(p, params={"serviceCode": "a" * 101}), "the API document states no outcome for an over-length code")


SUITES = [test_checks, test_decision_agreement]


if __name__ == "__main__":
    sys.exit(run(EXTRA_ARGS, preflight, SUITES))
